apiVersion: v1
kind: Service
metadata:
  name: html-demo-svc
  labels:
    app: html-demo
spec:
  type: NodePort    # change to LoadBalancer if your cluster supports it
  selector:
    app: html-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # for NodePort; choose a value in the allowed range

